# PACS generated

dataset: 'PACS' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: './datasets/neurips/new_generated/PACS/PACS_final_static_cot_50_sdxl_subsampled_filtered'
  dalle2: './datasets/neurips/new_generated/PACS/PACS_final_static_cot_50_dalle2_subsampled_filtered'
  floyd: './datasets/neurips/new_generated/PACS/PACS_final_static_cot_50_floyd_subsampled_filtered'
  cogview2: './datasets/neurips/new_generated/PACS/PACS_final_static_cot_50_cogview2_subsampled'

pickle_save_path: './RMD_scores/PACS_final_generated_RMD.pkl'
