# PACS generated

dataset: 'DomainNet' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: './datasets/neurips/new_generated/DomainNet/DomainNet_static_cot_50_sdxl_subsampled_filtered'
  dalle2: './datasets/neurips/new_generated/DomainNet/DomainNet_static_cot_50_dalle2_subsampled_filtered'
  floyd: './datasets/neurips/new_generated/DomainNet/DomainNet_static_cot_50_floyd_subsampled_filtered'
  cogview2: './datasets/neurips/new_generated/DomainNet/DomainNet_static_cot_50_cogview2_subsampled_filtered'

pickle_save_path: './RMD_scores/DomainNet_generated_RMD.pkl'
