# PACS generated

embedding_model: 'clip'
dataset: 'ImageNet' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: '/home/user/imagenet_ours/ImageNet_50_2_sdxl_subsampled_filtered'
  floyd: '/home/user/imagenet_ours/ImageNet_50_2_floyd_subsampled_filtered'
  cogview2: '/home/user/imagenet_ours/ImageNet_50_2_cogview2_subsampled_filtered'
  sd3: '/home/user/imagenet_ours/ImageNet_50_2_sd3_subsampled_filtered'
  auraflow: '/home/user/imagenet_ours/ImageNet_50_2_auraflow_subsampled_filtered'
json_save_path: './RMD_scores/ImageNet_50_2_sdxl_floyd_cogview2_sd3_auraflow.json'
