# PACS generated

dataset: 'PACS' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: './raw_datasets/iclr_generated/PACS/PACS_sdxl_subsampled_filtered'
  floyd: './raw_datasets/iclr_generated/PACS/PACS_floyd_subsampled_filtered'
  cogview2: './raw_datasets/iclr_generated/PACS/PACS_cogview2_subsampled_filtered'
  sdturbo: './raw_datasets/iclr_generated/PACS/PACS_sdturbo_subsampled_filtered'

pickle_save_path: './RMD_scores/PACS_final_sdturbo.pkl'
