# PACS generated

embedding_model: 'dinov2'
dataset: 'PACS' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: './raw_datasets/iclr_generated/PACS/PACS_sdxl_subsampled_filtered'
  floyd: './raw_datasets/iclr_generated/PACS/PACS_floyd_subsampled_filtered'
  cogview2: './raw_datasets/iclr_generated/PACS/PACS_cogview2_subsampled_filtered'
  # sdturbo: './raw_datasets/iclr_generated/PACS/PACS_sdturbo_subsampled_filtered'
  sd3: './raw_datasets/iclr_generated/PACS/PACS_sd3_subsampled_filtered'
  flux: './raw_datasets/iclr_generated/PACS/PACS_flux_subsampled_filtered'
  kolors: './raw_datasets/iclr_generated/PACS/PACS_kolors_subsampled_filtered'
  auraflow: './raw_datasets/iclr_generated/PACS/PACS_auraflow_subsampled_filtered'

json_save_path: './RMD_scores/PACS_sdxl_floyd_cogview2_sd3_flux_kolors_auraflow_dinov2_base.json'
