# PACS generated

embedding_model: 'clip'
dataset: 'PACS' # PACS, DomainNet, cifar10
use_ma_size: False
image_paths:
  sdxl: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_sdxl_subsampled_filtered'
  floyd: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_floyd_subsampled_filtered'
  cogview2: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_cogview2_subsampled_filtered'
  sd3: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_sd3_subsampled_filtered'
  flux: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_flux_subsampled_filtered'
  auraflow: './raw_datasets/iclr_generated/PACS/PACS_final_fake_f_auraflow_subsampled_filtered'

json_save_path: './RMD_scores/PACS_final_fake_f_sdxl_floyd_cogview2_sd3_flux_auraflow.json'
