dataset: cct
image_dir: ./CCT_cafo
generative_model: dalle2

# start_class: 0
# end_class: 1
debug: False

api_key: sk-proj-b6mF6aJroOzev4yh1afBT3BlbkFJcgqlS8S3hrxASu62u3a6 # For Dalle2

# prompt_dir: './prompts/clip_filtered_prompts.json'
prompt_dir: '../prompt_generation/prompts/cafo_a_photo_of_cct.json'
num_samples_path: none # txt file to run conveniently


# If you want to manually set the number of samples of each class...
# increase_ratio: 1.2 # MA * increase_ratio
# resume_prompt_idx: 1
num_samples_per_cls: 16 # Fix the number of samples per cls
# num_samples:
#   person: 100
#   horse: 100
