dataset: PACS
image_dir: ./generated_datasets/PACS_dalle2
generative_model: dalle2

start_class: 6
end_class: 6
debug: False
api_key: sk-proj-b6mF6aJroOzev4yh1afBT3BlbkFJcgqlS8S3hrxASu62u3a6 # For Dalle2

# prompt_dir: './prompts/clip_filtered_prompts.json'
prompt_dir: '../prompt_generation/prompts/gpt_static_totalprompts_with_cot_50_with_cls_PACS.json'
num_samples_path: none # txt file to run conveniently


# If you want to manually set the number of samples of each class...
increase_ratio: 1.2 # MA * increase_ratio
# resume_prompt_idx: 1
# num_samples_per_cls: 16 # Fix the number of samples per cls
# num_samples:
#   person: 100
#   horse: 100
